package com.vernanda.entity;
// Generated Apr 25, 2018 1:34:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClassScheduleId generated by hbm2java
 */
@Embeddable
public class ClassScheduleId  implements java.io.Serializable {


     private String classSelection;
     private boolean type;
     private String lecturerNik;
     private int roomId;
     private int academicYearId;
     private int semesterId;
     private String courseId;

    public ClassScheduleId() {
    }

    public ClassScheduleId(String classSelection, boolean type, String lecturerNik, int roomId, int academicYearId, int semesterId, String courseId) {
       this.classSelection = classSelection;
       this.type = type;
       this.lecturerNik = lecturerNik;
       this.roomId = roomId;
       this.academicYearId = academicYearId;
       this.semesterId = semesterId;
       this.courseId = courseId;
    }
   


    @Column(name="class_selection", nullable=false, length=1)
    public String getClassSelection() {
        return this.classSelection;
    }
    
    public void setClassSelection(String classSelection) {
        this.classSelection = classSelection;
    }


    @Column(name="type", nullable=false)
    public boolean isType() {
        return this.type;
    }
    
    public void setType(boolean type) {
        this.type = type;
    }


    @Column(name="lecturer_nik", nullable=false, length=8)
    public String getLecturerNik() {
        return this.lecturerNik;
    }
    
    public void setLecturerNik(String lecturerNik) {
        this.lecturerNik = lecturerNik;
    }


    @Column(name="room_id", nullable=false)
    public int getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(int roomId) {
        this.roomId = roomId;
    }


    @Column(name="academic_year_id", nullable=false)
    public int getAcademicYearId() {
        return this.academicYearId;
    }
    
    public void setAcademicYearId(int academicYearId) {
        this.academicYearId = academicYearId;
    }


    @Column(name="semester_id", nullable=false)
    public int getSemesterId() {
        return this.semesterId;
    }
    
    public void setSemesterId(int semesterId) {
        this.semesterId = semesterId;
    }


    @Column(name="course_id", nullable=false, length=5)
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClassScheduleId) ) return false;
		 ClassScheduleId castOther = ( ClassScheduleId ) other; 
         
		 return ( (this.getClassSelection()==castOther.getClassSelection()) || ( this.getClassSelection()!=null && castOther.getClassSelection()!=null && this.getClassSelection().equals(castOther.getClassSelection()) ) )
 && (this.isType()==castOther.isType())
 && ( (this.getLecturerNik()==castOther.getLecturerNik()) || ( this.getLecturerNik()!=null && castOther.getLecturerNik()!=null && this.getLecturerNik().equals(castOther.getLecturerNik()) ) )
 && (this.getRoomId()==castOther.getRoomId())
 && (this.getAcademicYearId()==castOther.getAcademicYearId())
 && (this.getSemesterId()==castOther.getSemesterId())
 && ( (this.getCourseId()==castOther.getCourseId()) || ( this.getCourseId()!=null && castOther.getCourseId()!=null && this.getCourseId().equals(castOther.getCourseId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getClassSelection() == null ? 0 : this.getClassSelection().hashCode() );
         result = 37 * result + (this.isType()?1:0);
         result = 37 * result + ( getLecturerNik() == null ? 0 : this.getLecturerNik().hashCode() );
         result = 37 * result + this.getRoomId();
         result = 37 * result + this.getAcademicYearId();
         result = 37 * result + this.getSemesterId();
         result = 37 * result + ( getCourseId() == null ? 0 : this.getCourseId().hashCode() );
         return result;
   }   


}


