package com.vernanda.entity;
// Generated Apr 25, 2018 1:34:17 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "ujitarobby_attendance_system"
)
public class Role implements java.io.Serializable {

    private int id;
    private String keterangan;
    private Set<Lecturer> lecturers = new HashSet<Lecturer>(0);

    public Role() {
    }

    public Role(int id) {
        this.id = id;
    }

    public Role(int id, String keterangan, Set<Lecturer> lecturers) {
        this.id = id;
        this.keterangan = keterangan;
        this.lecturers = lecturers;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "keterangan", length = 45)
    public String getKeterangan() {
        return this.keterangan;
    }

    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
    public Set<Lecturer> getLecturers() {
        return this.lecturers;
    }

    public void setLecturers(Set<Lecturer> lecturers) {
        this.lecturers = lecturers;
    }

}
