package com.vernanda.entity;
// Generated Apr 12, 2018 4:13:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name="room"
    ,catalog="ujitarobby_attendance_system"
)
public class Room  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<ClassSchedule> classSchedules = new HashSet<ClassSchedule>(0);

    public Room() {
    }

	
    public Room(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Room(int id, String name, Set<ClassSchedule> classSchedules) {
       this.id = id;
       this.name = name;
       this.classSchedules = classSchedules;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="room")
    public Set<ClassSchedule> getClassSchedules() {
        return this.classSchedules;
    }
    
    public void setClassSchedules(Set<ClassSchedule> classSchedules) {
        this.classSchedules = classSchedules;
    }




}


